# Generated by Django 3.1.3 on 2021-01-01 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 18, 2, 25, 456241)),
        ),
        migrations.AlterField(
            model_name='article',
            name='updater',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
