# Generated by Django 3.1.3 on 2021-01-01 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210101_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 18, 3, 7, 24503)),
        ),
    ]
