# Generated by Django 3.1.3 on 2021-01-02 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210101_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('contrib', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 1, 2, 18, 46, 3, 948831))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 18, 46, 3, 947585)),
        ),
    ]
